### ISSUE TITLE
Handle server setup container

### ISSUE THREAD

**Issue by bitfield** [rpidproject/puppet#3]
Build and run a container which creates the Handle Server sitebndl.zip file.

- [x] Install Handle Server
- [x] Create public and private keys
- [x] Create siteinfo file
- [x] Convert siteinfo to bin
- [x] Zip up sitebndl.zip file

**Comment by balmas** [comment]
- [ ] item 1

**Comment by balmas** [comment]
Configuration to come from puppet (to feed into template files used in install)
- [x] download url
- [x] handle server version
- [x] java version
- [x] prefix
- [x] primary vs mirror
- [ ] dual-stack
- [x] ip address for client network connection
- [x] ip address for binding
- [x] tcp/port number (default 2641)
- [x] HTTP port
- [x] log accesses?
- [x] log rotation schedule
- [ ] site version/serial number (default 1)
- [x] description of site
- [ ] organization name
- [x] contact name
- [x] telephone number organization
- [x] telephone number contact
- [ ] disable UDP?

**Comment by balmas** [comment]
Questions:
- [ ] what is meaning of site/version serial number

**Comment by balmas** [comment]
this is done. additional tweaks will result in new issues.
